#pragma config(Motor,  port5,           rightTop,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           rightBottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port2,           leftTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mogoLeftLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           coneRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           coneLeftLift,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void assignMotorSpeed (tMotor motor1, tMotor motor2, int speed){
	motor[motor1] = speed;
	motor[motor2] = speed;
}

bool btnNumMogo = false;
bool btnNumCone = false;
bool btnTap = false;
bool turnOnMotors = false;

task sustainMogo(){
	while(true){
		/*if(vexRT[Btn8U]){
		count = 1;
		}
		while(count%2 == 1){
		assignMotorSpeed(mogoRightLift,mogoLeftLift,50);
		count++;
		}*/
		if(vexRT[Btn8U]){
			if(!btnTap){ //not of false is true
				turnOnMotors = !turnOnMotors;
				btnTap = true;
			}
			else{
				btnTap = false;
				turnOnMotors = false;
			}
		}
		if(turnOnMotors){
			assignMotorSpeed(mogoRightLift,mogoLeftLift,50);
		}
		else{
			assignMotorSpeed(mogoRightLift,mogoLeftLift,0);
		}
	}
}

task main()
{
	startTask(sustainMogo);
	while(true){
		motor[rightTop] = vexRT[Ch2];
		motor[rightBottom] = vexRT[Ch2];
		motor[leftTop] = vexRT[Ch3];
		motor[leftBottom] = vexRT[Ch3];

		assignMotorSpeed(mogoRightLift,mogoLeftLift,0);
		assignMotorSpeed(coneRightLift,coneLeftLift,0);

		switch(vexRT[btnNumMogo]){
		case Btn6U:
			assignMotorSpeed(mogoRightLift,mogoLeftLift,80);
			break;
		case Btn6D:
			assignMotorSpeed(mogoRightLift,mogoLeftLift,-80);
			break;
		case Btn8U:
			startTask(sustainMogo);
		default:
			assignMotorSpeed(mogoRightLift,mogoLeftLift,0);
		}

		switch(vexRT[btnNumCone]){
		case Btn5U:
			assignMotorSpeed(coneRightLift,coneLeftLift,90);
			break;
		case Btn5D:
			assignMotorSpeed(coneRightLift,coneLeftLift,-90);
			break;
		default:
			assignMotorSpeed(coneRightLift,coneLeftLift,0);
		}

		/*
		motor[mogoRightLift] = 0;
		motor[mogoRightLift] = 0;
		motor[mogoConeLift] = 0;
		motor[mogoConeLift] = 0;

		if(vexRT[Btn6U]){
		assignMotorSpeed(mogoRightLift,mogoLeftLift,80);
		}
		else if(vexRT[Btn6D]){
		assignMotorSpeed(mogoRightLift,mogoLeftLift,-80);
		}

		if(vexRT[Btn5U]){
		assignMotorSpeed(coneRightLift,coneLeftLift,90);
		}
		else if(vexRT[Btn5D]){
		assignMotorSpeed(coneRightLift,coneLeftLift,-90);
		}
		if(vexRT[Btn8U]){
		assignMotorSpeed(mogoRightLift,mogoLeftLift,50);
		}
		else if(vexRT[Btn8R]){
		assignMotorSpeed(mogoRightLift,mogoLeftLift,0);
		}
		if(vexRT[Btn7U]){
		assignMotorSpeed(coneRightLift,coneLeftLift,40);
		}
		else if(vexRT[Btn7L]){
		assignMotorSpeed(coneRightLift,coneLeftLift,0);
		}*/

	}

}
