#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveTheDrive(){
	motor[frontLeft] = 127;
	motor[backLeft] = 127;
	motor[backRight] = 127;
	motor[frontRight] = 127;
}
void reverseTheDrive() {
	motor[frontLeft] = -127;
	motor[backLeft] = -127;
	motor[backRight] = -127;
	motor[frontRight] = -127;
}
void stopTheDrive(){
	motor[frontLeft] = 0;
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
task main()
{



}
