#pragma config(Sensor, in1,    coneLift,       sensorPotentiometer)
#pragma config(Sensor, in2,    mogoLift,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  drive,          sensorQuadEncoder)
#pragma config(Motor,  port2,           leftTop,       tmotorVex393_MC29, openLoop,)
#pragma config(Motor,  port1,           rightBottom,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightTop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mogoRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mogoLeftLift,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           coneRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           coneLeftLift,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,          coneIntake,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

float distToMogo = 1200; //72in divided by 4pi in. wheel revolutions of 360 deg
float distTo10Zone = 0;
//float distTo20Zone = 0;
//float encoderVal = 0;
int targetMogoLiftUp = 0;
int targetMogoLiftDown = 0;
float conePotVal = 0; //to be determined from testing or other groups
// for PID if necessary
int targetConeLiftUp = 0;
int targetConeLiftDown = 0;
//int targetDrive = 0;

// .8*127 = 101.6 ~~ 102
void turnOnDriveMotors(){
	motor[rightTop] = 102;
	motor[rightBottom] = 102;
	motor[leftTop] = 102;
	motor[leftBottom] = 102;
}
void turnOffDriveMotors(){
	motor[rightTop] = 0;
	motor[rightBottom] = 0;
	motor[leftTop] = 0;
	motor[leftBottom] = 0;
}
void reverseDriveMotors(){
	motor[rightTop] = -102;
	motor[rightBottom] = -102;
	motor[leftTop] = -102;
	motor[leftBottom] = -102;
}
void turnAround(){
	int turnTarget = SensorValue[drive] + (360*(11.25/4));
	int error = turnTarget - SensorValue[drive];
	motor[leftBottom] = 0.1 * error;
	motor[leftTop] = 0.1 * error;
}
void liftMogoUp(){
	motor[mogoRightLift] = 102;
	motor[mogoLeftLift] = 102;
	wait1Msec(1500);
}
/*void stopMogoMotors(){
motor[mogoRightLift] = 0;
motor[mogoLeftLift] = 0;
}*/
void keepMogoUp(){
	motor[mogoRightLift] = 70;
	motor[mogoLeftLift] = 70;
}
void bringMogoDown(){
	motor[mogoRightLift] = -102;
	motor[mogoLeftLift] = -102;
	wait1Msec(1500);
}


void assignMotorSpeed (tMotor motor1, tMotor motor2, int speed){
	motor[motor1] = speed;
	motor[motor2] = speed;
}

bool btnNumMogo = false;
bool btnNumCone = false;

float currVal = SensorValue[drive];

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	SensorValue[coneLift] = 0;
	SensorValue[mogoLift] = 0;
	SensorValue[drive] = 0;

	/* distToMogo = 1200; //72in divided by 4pi in. wheel revolutions of 360 deg
	float distTo10Zone = 0;
	//float distTo20Zone = 0;
	//float encoderVal = 0;
	int targetMogoLiftUp = 0;
	int targetMogoLiftDown = 0;
	float conePotVal = 0; //to be determined from testing or other groups
	// for PID if necessary
	int targetConeLiftUp = 0;
	int targetConeLiftDown = 0;*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//int targetDrive = 0;

// .8*127 = 101.6 ~~ 10

task autonomous()
{/*
	while(true){
		bringMogoDown();
		while(SensorValue[drive] < distToMogo){
			turnOnDriveMotors();
//wait1Msec(20);
		}
		turnOffDriveMotors();
		wait1Msec(5);
		liftMogoUp();
		wait1Msec(5000);
		keepMogoUp();
		wait1Msec(5000);
		/*
		* If turning after picking up mogo*/
	/*	turnAround();
		/*Adjust value of 'distTo10Zone' if we can't do a turn in place
		*/
		/*while(SensorValue[drive] > 400){ // value can be changed to suit 20 point zone
			reverseDriveMotors();
			wait10Msec(1);
		}*/		/*
		* If turning after returning to point zone
		* turnAround();
		* Might have to go foreward a little
		*/
		//bringMogoDown();

	//}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{
	while(true){
		int leftPower = vexRT(Ch3);  //*.8
		if(abs(leftPower) < 20) {
			leftPower = 0;
		}
		int rightPower = vexRT(Ch2); //*.8
		if(abs(rightPower) < 20) {
			rightPower = 0;
		}
		assignMotorSpeed(rightTop,rightBottom,rightPower);
		assignMotorSpeed(leftTop,leftBottom,leftPower);

		assignMotorSpeed(mogoRightLift,mogoLeftLift,0);
		assignMotorSpeed(coneRightLift,coneLeftLift,0);

		/*(vexRT[Btn7D]) {
		startTask(auton);
		}
		stopTask(auton);*/

		if(vexRT[Btn6U]){

			assignMotorSpeed(mogoRightLift,mogoLeftLift,80);
		}
		else if(vexRT[Btn6D]){
			assignMotorSpeed(mogoRightLift,mogoLeftLift,-80);
		}

		if(vexRT[Btn5U]){
			assignMotorSpeed(coneRightLift,coneLeftLift,90);
		}
		else if(vexRT[Btn5D]){
			assignMotorSpeed(coneRightLift,coneLeftLift,-90);
		}
		if(vexRT[Btn8U]){
		motor[coneIntake] = 35;
		}
		else if(vexRT[Btn8D]){
				motor[coneIntake] = -35;
		}

	}



}
